version: '3.8'

services:
  backend:
    build:
      context: ./back
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
      POSTGRES_DB: spweb
    ports:
      - "8432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

volumes:
  pgdata:
    driver: local