"""added date

Revision ID: 5266c0b2be3d
Revises: 693b8f7c8cc3
Create Date: 2024-11-24 15:24:32.942046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5266c0b2be3d'
down_revision: Union[str, None] = '693b8f7c8cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_of_event', postgresql.ENUM('BIRTHDAY', 'AWARD', 'DISCOVERY', name='event_type_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date')
    # ### end Alembic commands ###
