"""add imageid to member

Revision ID: 69a827c4d166
Revises: c81cb8e4a3e3
Create Date: 2024-09-28 16:33:19.272260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a827c4d166'
down_revision: Union[str, None] = 'c81cb8e4a3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('image_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'image_id')
    # ### end Alembic commands ###
